format = """
$python\
$git_branch\
$git_status\
$character
"""

right_format = """
$time
"""

add_newline = false

[git_branch]
# symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '

[character]
format = '$symbol '
success_symbol = '[➜](bold green)' 
error_symbol = '[!](bold red)'

[python]
symbol = ' '
format = '[(\($virtualenv\) )]($style)'
version_format = '${raw}'
style = 'yellow bold'

[time]
style = 'blue'
disabled = false
format = '[$time]($style)'
