setopt auto_cd
setopt correct
setopt correct_all
setopt extended_history
setopt hist_expand
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_no_store
setopt hist_reduce_blanks
setopt inc_append_history
setopt interactive_comments
setopt list_packed      
#setopt auto_pushd
#setopt pushd_ignore_dups
setopt no_beep
setopt share_history
setopt noautoremoveslash
setopt auto_param_slash
